# Generated by Django 4.2.30 on 2026-04-29 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_videocomment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videocomment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
